package com.myspace.customer_onboarding;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.xml.bind.annotation.XmlRootElement
public class Customer implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Name")
	private java.lang.String name;
	@org.kie.api.definition.type.Label("Age")
	private java.lang.String age;
	@org.kie.api.definition.type.Label(value = "ID")
	private java.lang.String id;

	public Customer() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getAge() {
		return this.age;
	}

	public void setAge(java.lang.String age) {
		this.age = age;
	}

	public java.lang.String getId() {
		return this.id;
	}

	public void setId(java.lang.String id) {
		this.id = id;
	}

	public Customer(java.lang.String name, java.lang.String age,
			java.lang.String id) {
		this.name = name;
		this.age = age;
		this.id = id;
	}

}